name: Build DemoIccMAX

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run DemoIccMAX Build Script
        run: |
          cd contrib/Build/cmake
          /bin/zsh xnu_build_master_branch.zsh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DemoIccMAX-build
          path: /tmp/DemoIccMAX
