name: Build and Upload Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Homebrew Dependencies
        run: brew install nlohmann-json libxml2 wxwidgets libtiff

      - name: Build Project
        run: |
          cd Build
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_CXX_FLAGS="-Wall" \
                -DCMAKE_INSTALL_RPATH="@executable_path" \
                -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
                -Wno-dev Cmake/
          make -j$(sysctl -n hw.ncpu)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: Build
